### ISSUE TITLE
[ERR] Failed to get OS version information on Debian stretch

### ISSUE THREAD

**Issue by KI5JYD** [foospidy/HoneyMiner#1]
Seems this issue at https://honeyminer.canny.io/troubleshooting/p/hmlabs-install-problem is being ignored....

Let me put it to y'all: ***Ubuntu IS based upon Debian!!!*** [1] [2] So please fix this problem.

Google is **NOT** helping. I have no idea what you need to fix this.
[1] https://www.ubuntu.com/community/debian
[2] https://www.debian.org/derivatives/

So, please don't hate against the people who decide to use "pure" Debian. Ubuntu == Debian.

**Comment by foospidy** [comment]
Hi, it would seem the HoneyMiner you are working with is a different project- https://honeyminer.com/. This repo is not related to https://honeyminer.com/. Given this repo has the same name as that project, sorry for the confusion. But looks like you can submit your request on their site here https://honeyminer.zendesk.com/hc/en-us/requests/new

Happy Mining!
